name: Build TWRP for angelican

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile TWRP Recovery
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Установка прав на build.sh
        run: chmod +x build.sh

      - name: Запуск build.sh
        run: ./build.sh

      - name: Загрузка артефакта
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-angelican
          path: platform_manifest_twrp_omni/out/target/product/angelican/TWRP_angelican_*.zip
